<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ref_aplikasi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ref_aplikasi_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $id=1;
		$row = $this->Ref_aplikasi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Simpan',
                'action' => site_url('ref_aplikasi/update_action'),
		'id' => set_value('id', $row->id),
		'nama_web' => set_value('nama_web', $row->nama_web),
		'nama_instansi' => set_value('nama_instansi', $row->nama_instansi),
		'alamat' => set_value('alamat', $row->alamat),
		'email' => set_value('email', $row->email),
		'fax' => set_value('fax', $row->fax),
		'no_telpn' => set_value('no_telpn', $row->no_telpn),
        'fb' => set_value('fb', $row->fb),
        'ig' => set_value('ig', $row->ig),
        'twitter' => set_value('twitter', $row->twitter),
        'yt' => set_value('yt', $row->yt),
	    );
            
			$this->template->load('backend/template','backend/ref_aplikasi/ref_aplikasi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('ref_aplikasi'));
        }
    }

    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            redirect(site_url('ref_aplikasi'));
        } else {
            $data = array(
		'nama_web' => $this->input->post('nama_web',TRUE),
		'nama_instansi' => $this->input->post('nama_instansi',TRUE),
		'alamat' => $this->input->post('alamat',TRUE),
		'email' => $this->input->post('email',TRUE),
		'fax' => $this->input->post('fax',TRUE),
		'no_telpn' => $this->input->post('no_telpn',TRUE),
        'fb' => $this->input->post('fb',TRUE),
        'ig' => $this->input->post('ig',TRUE),
        'twitter' => $this->input->post('twitter',TRUE),
        'yt' => $this->input->post('yt',TRUE),

	    );

            $this->Ref_aplikasi_model->update("1", $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('ref_aplikasi'));
        }
    }
    
    public function _rules() 
    {
	$this->form_validation->set_rules('nama_web', 'nama web', 'trim|required');
	$this->form_validation->set_rules('nama_instansi', 'nama instansi', 'trim|required');
	$this->form_validation->set_rules('alamat', 'alamat', 'trim|required');
	$this->form_validation->set_rules('email', 'email', 'trim|required');
	$this->form_validation->set_rules('fax', 'fax', 'trim|required');
	$this->form_validation->set_rules('no_telpn', 'no telpn', 'trim|required');
    $this->form_validation->set_rules('fb', 'Facebook', 'trim');
    $this->form_validation->set_rules('ig', 'Instagram', 'trim');
    $this->form_validation->set_rules('twitter', 'Twitter', 'trim');
    $this->form_validation->set_rules('yt', 'Youtube', 'trim');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Ref_aplikasi.php */
/* Location: ./application/controllers/Ref_aplikasi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-20 09:17:08 */
/* http://harviacode.com */