<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ref_visimisi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ref_visimisi_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'ref_visimisi/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'ref_visimisi/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'ref_visimisi/index.html';
            $config['first_url'] = base_url() . 'ref_visimisi/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Ref_visimisi_model->total_rows($q);
        $ref_visimisi = $this->Ref_visimisi_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'ref_visimisi_data' => $ref_visimisi,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('ref_visimisi/ref_visimisi_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Ref_visimisi_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'visimisi' => $row->visimisi,
	    );
            $this->load->view('ref_visimisi/ref_visimisi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('ref_visimisi'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('ref_visimisi/create_action'),
	    'id' => set_value('id'),
	    'visimisi' => set_value('visimisi'),
	);
        $this->load->view('ref_visimisi/ref_visimisi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'visimisi' => $this->input->post('visimisi',TRUE),
	    );

            $this->Ref_visimisi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('ref_visimisi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Ref_visimisi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('ref_visimisi/update_action'),
		'id' => set_value('id', $row->id),
		'visimisi' => set_value('visimisi', $row->visimisi),
	    );
			$this->template->load('backend/template','backend/ref_visimisi/ref_visimisi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('backend'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'visimisi' => $this->input->post('visimisi',TRUE),
	    );

            $this->Ref_visimisi_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('backend'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Ref_visimisi_model->get_by_id($id);

        if ($row) {
            $this->Ref_visimisi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('ref_visimisi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('ref_visimisi'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('visimisi', 'visimisi', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Ref_visimisi.php */
/* Location: ./application/controllers/Ref_visimisi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-22 23:39:54 */
/* http://harviacode.com */