<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Reg_pak_model extends CI_Model
{

    public $table = 'reg_pak';
    public $id = 'reg_pak';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('reg_pak', $q);
	$this->db->or_like('id_pegawai', $q);
	$this->db->or_like('id_golongan', $q);
	$this->db->or_like('id_periode', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('tahap', $q);
	$this->db->or_like('tgl_daftar', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('reg_pak', $q);
	$this->db->or_like('id_pegawai', $q);
	$this->db->or_like('id_golongan', $q);
	$this->db->or_like('id_periode', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('tahap', $q);
	$this->db->or_like('tgl_daftar', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Reg_pak_model.php */
/* Location: ./application/models/Reg_pak_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-19 08:55:34 */
/* http://harviacode.com */