<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ta_berita_model extends CI_Model
{

    public $table = 'ta_berita';
    public $id = 'id_berita';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->select('ta_berita.id_berita, ta_berita.judul, ta_berita.isi, ta_berita.jenis_berita, ta_berita.tgl_insert, ta_berita.tgl_update, ta_berita.user, ta_berita.viewer, ta_berita.file,
            ref_kategori_berita.id_kategori, ref_kategori_berita.kategori
                    ');
         $or_like ='(ref_kategori_berita.kategori LIKE "%'.$q.'%"
                    OR ta_berita.judul LIKE "%'.$q.'%"
                    OR ta_berita.isi LIKE "%'.$q.'%"
                    )';
        $this->db->join('ref_kategori_berita', 'ta_berita.jenis_berita=ref_kategori_berita.id_kategori', 'left');
        $this->db->where($or_like);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('ta_berita.id_berita, ta_berita.judul, ta_berita.isi, ta_berita.jenis_berita, ta_berita.tgl_insert, ta_berita.tgl_update, ta_berita.user, ta_berita.viewer, ta_berita.file,
            ref_kategori_berita.id_kategori, ref_kategori_berita.kategori
                    ');
         $or_like ='(ref_kategori_berita.kategori LIKE "%'.$q.'%"
                    OR ta_berita.judul LIKE "%'.$q.'%"
                    OR ta_berita.isi LIKE "%'.$q.'%"
                    )';
        $this->db->join('ref_kategori_berita', 'ta_berita.jenis_berita=ref_kategori_berita.id_kategori', 'left');
        $this->db->where($or_like);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ta_berita_model.php */
/* Location: ./application/models/Ta_berita_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-21 13:22:41 */
/* http://harviacode.com */