<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ta_produk_hukum_det_model extends CI_Model
{

    public $table = 'ta_produk_hukum_det';
    public $id = 'id_produk_hukum';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id_produk_hukum_subject)
    {
        $this->db->where(['id_produk_hukum'=>$id_produk_hukum_subject, 
                'id_sumber_perubahan'=>'0']);
        return $this->db->get($this->table)->row();
    }

     function periksa_status($id_produk_hukum)
    {
        $this->db->where('id_produk_hukum', $id_produk_hukum);
        return $this->db->get($this->table)->row();
    }

     function get_sumber($id_produk_hukum)
    {
        $this->db->where('id_sumber_perubahan', $id_produk_hukum);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_produk_hukum', $q);
	$this->db->or_like('id_status_peraturan', $q);
	$this->db->or_like('file_sumber_perubahan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk_hukum', $q);
	$this->db->or_like('id_status_peraturan', $q);
	$this->db->or_like('file_sumber_perubahan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    

    // insert data
    function insert($data_perubahan)
    {
        $this->db->insert($this->table, $data_perubahan);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function update_perubahan($id, $data_perubahan)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data_perubahan);
    }

}

/* End of file Ta_produk_hukum_det_model.php */
/* Location: ./application/models/Ta_produk_hukum_det_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-23 15:48:51 */
/* http://harviacode.com */