<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ta_produk_hukum_katalog_model extends CI_Model
{

    public $table = 'ta_produk_hukum_katalog';
    public $id = 'id_produk_hukum';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_produk_hukum', $q);
	$this->db->or_like('ktlglembaran_jenis', $q);
	$this->db->or_like('ktlglembaran_tahun', $q);
	$this->db->or_like('ktlglembaran_no', $q);
	$this->db->or_like('ktlglembaran_jum_halaman', $q);
	$this->db->or_like('ktlgtambahan_jenis', $q);
	$this->db->or_like('ktlgtambahan_tahun', $q);
	$this->db->or_like('ktlgtambahan_no', $q);
	$this->db->or_like('ktlgtambahan_jum_halaman', $q);
	$this->db->or_like('pemrakarsa', $q);
	$this->db->or_like('no_register', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk_hukum', $q);
	$this->db->or_like('ktlglembaran_jenis', $q);
	$this->db->or_like('ktlglembaran_tahun', $q);
	$this->db->or_like('ktlglembaran_no', $q);
	$this->db->or_like('ktlglembaran_jum_halaman', $q);
	$this->db->or_like('ktlgtambahan_jenis', $q);
	$this->db->or_like('ktlgtambahan_tahun', $q);
	$this->db->or_like('ktlgtambahan_no', $q);
	$this->db->or_like('ktlgtambahan_jum_halaman', $q);
	$this->db->or_like('pemrakarsa', $q);
	$this->db->or_like('no_register', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ta_produk_hukum_katalog_model.php */
/* Location: ./application/models/Ta_produk_hukum_katalog_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-25 17:36:24 */
/* http://harviacode.com */